In [1]:
import random as r

In [5]:
print(int(r.random())*10+1)

1

In [7]:
# 난수를 이용해서 리스트 생성
list_scores = []
for s in range(0,10):
    list_scores.append(r.randint(60,100))

print(list_scores)

[63, 69, 88, 78, 64, 89, 60, 100, 78, 77]

In [12]:
r.choice(list_scores)

78

In [22]:
r.sample(list_scores,5)

[78, 64, 88, 60, 63]

In [23]:
import os

In [ ]:
os.environ

In [ ]:
# 현재 진행 중인 디렉토리 경로를 보여준다
os.getcwd()

'c:\\python_project'

In [ ]:
# 현재 경로에 디렉토리 생성
os.mkdir('test')

In [ ]:
# 현재 경로에 디렉토리 삭제
os.rmdir('test')

In [28]:
import json

In [31]:
with open('data.json', 'r', encoding="utf-8") as f:
    # str(json) => list
    data = json.load(f)
    print(data, type(data))

[{'name': 'COOL', 'age': 25}] <class 'list'>

In [33]:
# list => str
json_str_data = json.dumps(data)
print(json_str_data, type(json_str_data))

[{"name": "COOL", "age": 25}] <class 'str'>

### 외부모듈

In [3]:
import numpy as np

In [38]:
# ndarray : 넘파이의 배열
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>

In [42]:
# 배열 생성
zeros = np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [44]:
ones = np.ones((3,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [51]:
# 일련번호로 된 배열 생성
seq1 = np.arange(1,10,3)
seq2 = np.arange(start=1,step=3, stop=10)
print(seq1)
print(seq2)

[1 4 7]
[1 4 7]

In [57]:
# 지정된 범위 안에 동일한 간격으로 숫자를 생성

linspace = np.linspace(1,20,5)
print(linspace)

[ 1.    5.75 10.5  15.25 20.  ]

In [ ]:
# 속성확인

list_temp =[
    [1,2,3],
    [4,5,6]
]
arr1 = np.array(list_temp)

#print(arr1)
print(arr1.shape)   # 배열의 사이즈 : (행, 열)
print(arr1.ndim)    # 배열의 차원
print(arr1.size)    # 전체 요소의 개수
print(arr1.dtype)   # 데이터의 타입

(2, 3)
2
6
int64

In [73]:
# 배열의 인덱싱과 슬라이싱 => List와 같다
arr2 = np.array([10, 20, 30, 40])

print(arr2[2])
print(arr2[3])
print(arr2[-1])

30
40
40

In [78]:
print(arr1)
print(arr1[0], type(arr1[0]))
print(arr1[0][0], type(arr1[0][0]))

[[1 2 3]
 [4 5 6]]
[1 2 3] <class 'numpy.ndarray'>
1 <class 'numpy.int64'>

In [79]:
arr3 = np.array([10, 20, 30, 40, 50])

In [84]:
print(arr3[:])
print(arr3[1:4])
print(arr3[1:])
print(arr3[-3:-1])

[10 20 30 40 50]
[20 30 40]
[20 30 40 50]
[30 40]

In [103]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

print(arr[0:2, 1:])

[[2 3]
 [5 6]]

In [ ]:
# 배열의 연산 : +, *, ** 리스트처럼 배열 자체를 여러 번 반복하는게 아닌 값을 더하고 곱하고 제곱한다.
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [111]:
print(arr2 + 10)
print(arr2 * 10)
print(arr2 **2)
print(arr1 + arr2)

[14 15 16]
[40 50 60]
[16 25 36]
[5 7 9]

In [4]:
# 배열의 구조(차원) 변경 : 1->2, 2->1
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)

In [5]:
# 1 -> 2
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr, reshaped_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)

In [6]:
# 2 -> 1
flated_arr = reshaped_arr.flatten()
print(flated_arr)

[1 2 3 4 5 6]

In [7]:
# 필터링
arr = np.array([1,2,3,4,5,6])
filtered_arr = arr[arr>3]
print(filtered_arr)

[4 5 6]

In [12]:
# 난수를 생성해서 배열 생성
ran_arr1 = np.random.rand(10)
ran_arr2 = np.random.randint(1,45, size=(5,6))
print(f'{ran_arr1}\n')
print(ran_arr2)

[0.07233395 0.36231115 0.12629909 0.12072379 0.12828633 0.48654078
 0.11136364 0.31798235 0.26637437 0.15550055]

[[25  5 31 31 44  8]
 [11 20 12 19 11 39]
 [38 17 32 18 18 21]
 [ 3 19 35  3  2 37]
 [30  1 39 27 39 38]]

### Pandas

In [7]:
import pandas as pd

# DataFrame : 2차원 형식의 표 모양으로 데이터 구조를 생성
data = {
    'Name' : ['정병규','한로로','아이유'],
    'Age' : [20,30,25]
}

df = pd.DataFrame(data)

print(df, type(df))

  Name  Age
0  정병규   20
1  한로로   30
2  아이유   25 <class 'pandas.DataFrame'>

In [13]:
df.head(2)

  Name  Age
0  정병규   20
1  한로로   30

In [12]:
df.tail(1)

  Name  Age
2  아이유   25

In [14]:
df.shape

(3, 2)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [ ]:
# 기초 통계 지표 ( 숫자 데이터 )
df.describe()

        Age
count   3.0
mean   25.0
std     5.0
min    20.0
25%    22.5
50%    25.0
75%    27.5
max    30.0

In [20]:
print(df['Age'].sum())
print(df['Age'].mean())

75
25.0

In [22]:
data = {
    'name' : ['cool', 'hot', 'king'],
    'age' : [20, 30 ,75],
    'score' : [90, 70 ,60]
}

df = pd.DataFrame(data)

In [25]:
print(df)

   name  age  score
0  cool   20     90
1   hot   30     70
2  king   75     60

In [26]:
df['age']

0    20
1    30
2    75
Name: age, dtype: int64

In [28]:
df.loc[2, 'score'] = 80
print(df)

   name  age  score
0  cool   20     90
1   hot   30     70
2  king   75     80

In [29]:
df.isnull()

    name    age  score
0  False  False  False
1  False  False  False
2  False  False  False